### ISSUE TITLE
Update Fattmerchant references to Stax

### ISSUE THREAD

**Issue by DanielBolef** [bdukes/PowerShellModules#16]
DNN-Restore prints this error because it is looking for SQL columns that have been renamed:
```
Invoke-Sqlcmd : Invalid column name 'MerchantRegistrationStatusId'.
Invalid column name 'FattmerchantMerchantId'.
Invalid column name 'FattmerchantApiKey'.
Invalid column name 'FattmerchantPaymentsToken'.
 Msg 207, Level 16, State 1, Procedure , Line 1.
```
Need to target the new column names.

**Comment by bdukes** [comment]
Do you want to submit a PR for that? Or do you know the new column names?

**Comment by DanielBolef** [comment]
No PR. I'm not sure what table `MerchantRegistrationStatusId` is from, but the other three are now:
```
StaxMerchantId
StaxApiKey
StaxPaymentsToken
```
