### ISSUE TITLE
Why was Recycle removed from PSGallery?

### ISSUE THREAD

**Issue by silverqx** [bdukes/PowerShellModules#29]
It's not published anymore [here](https://www.powershellgallery.com/packages?q=recycle).

**Comment by bdukes** [comment]
#18 and #28 highlight some major flaws in its design, so I've unpublished it until those can be resolved.

**Comment by bdukes** [comment]
No, I'm not aware of an alternative. Sorry!

**Comment by silverqx** [comment]
Thx, it looks like there isn't any, it would be worth the effort to fix Recycle as there is no alternative.

**Comment by bdukes** [comment]
I believe the ideal implementation would use similar APIs to https://github.com/sindresorhus/recycle-bin (or even use that binary directly), and never fall-back to full deleting.

I don't have availability to investigate and implement further, but definitely willing to review contributions from anyone willing to contribute.

**Comment by silverqx** [comment]
Ok, thx
