### ISSUE TITLE
Recycle on Linux

### ISSUE THREAD

**Issue by Konfekt** [bdukes/PowerShellModules#7]
Just wondering, as their aren't any documented restrictions on the operating system for the use of Recyle. Does [the use](https://github.com/bdukes/PowerShellModules/blob/4de3e103fe7ac4d4b92adc623b6462d29f991bc9/Recycle/Recycle.psm1#L117) of `New-Object -ComObject "Shell.Application"` introduce a dependency on Microsoft Windows?

**Comment by bdukes** [comment]
Yes, there is a Windows dependency. I've added tags so that is shows correctly in the PowerShell Gallery. Thanks!
